###############################################################################
## Organization
###############################################################################
organizations:
    pattern: /organizations
    defaults: { _controller: VolleyballOrganizationBundle:Organization:index }
organization_show:
    pattern: /organizations/{organization}
    defaults: { _controller: VolleyballOrganizationBundle:Organization:show }
organization_new:
    pattern: /organizations/new
    defaults: { _controller: VolleyballOrganizationBundle:Organization:new }
organization_edit:
    pattern: /organizations/{organization}/edit
    defaults: { _controller: VolleyballOrganizationBundle:Organization:edit }

###############################################################################
## Council
###############################################################################
councils:
    pattern: /councils
    defaults: { _controller: VolleyballOrganizationBundle:Council:index }
councils_by_organization:
    pattern: /organizations/{organization}/councils
    defaults: { _controller: VolleyballOrganizationBundle:Council:organization }
councils_show:
    pattern: /councils/{council}
    defaults: { _controller: VolleyballOrganizationBundle:Council:show }
councils_new:
    pattern: /councils/new
    defaults: { _controller: VolleyballOrganizationBundle:Council:new }
councils_edit:
    pattern: /councils/{council}/edit
    defaults: { _controller: VolleyballOrganizationBundle:Council:edit }
