<?php

namespace Volleyball\FacilityBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:58.
 */
class DepartmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Department
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Department;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getDepartment
     * @todo   Implement testGetDepartment().
     */
    public function testGetDepartment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setDepartment
     * @todo   Implement testSetDepartment().
     */
    public function testSetDepartment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setFacility
     * @todo   Implement testSetFacility().
     */
    public function testSetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Department::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}