<?php

namespace Volleyball\FacilityBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:59.
 */
class FacilityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Facility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Facility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getAddress
     * @todo   Implement testGetAddress().
     */
    public function testGetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setAddress
     * @todo   Implement testSetAddress().
     */
    public function testSetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getOrganization
     * @todo   Implement testGetOrganization().
     */
    public function testGetOrganization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setOrganization
     * @todo   Implement testSetOrganization().
     */
    public function testSetOrganization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getCouncil
     * @todo   Implement testGetCouncil().
     */
    public function testGetCouncil()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setCouncil
     * @todo   Implement testSetCouncil().
     */
    public function testSetCouncil()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getRegion
     * @todo   Implement testGetRegion().
     */
    public function testGetRegion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setRegion
     * @todo   Implement testSetRegion().
     */
    public function testSetRegion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setFaculty
     * @todo   Implement testSetFaculty().
     */
    public function testSetFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::hasFaculty
     * @todo   Implement testHasFaculty().
     */
    public function testHasFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getFaculty
     * @todo   Implement testGetFaculty().
     */
    public function testGetFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::addFaculty
     * @todo   Implement testAddFaculty().
     */
    public function testAddFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::removeFaculty
     * @todo   Implement testRemoveFaculty().
     */
    public function testRemoveFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getQuarters
     * @todo   Implement testGetQuarters().
     */
    public function testGetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getDepartments
     * @todo   Implement testGetDepartments().
     */
    public function testGetDepartments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setDepartments
     * @todo   Implement testSetDepartments().
     */
    public function testSetDepartments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::hasDepartments
     * @todo   Implement testHasDepartments().
     */
    public function testHasDepartments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getDepartment
     * @todo   Implement testGetDepartment().
     */
    public function testGetDepartment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::addDepartment
     * @todo   Implement testAddDepartment().
     */
    public function testAddDepartment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::removeDepartment
     * @todo   Implement testRemoveDepartment().
     */
    public function testRemoveDepartment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getSeasons
     * @todo   Implement testGetSeasons().
     */
    public function testGetSeasons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setSeasons
     * @todo   Implement testSetSeasons().
     */
    public function testSetSeasons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::hasSeasons
     * @todo   Implement testHasSeasons().
     */
    public function testHasSeasons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getSeason
     * @todo   Implement testGetSeason().
     */
    public function testGetSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::addSeason
     * @todo   Implement testAddSeason().
     */
    public function testAddSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::removeSeason
     * @todo   Implement testRemoveSeason().
     */
    public function testRemoveSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setQuarters
     * @todo   Implement testSetQuarters().
     */
    public function testSetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\FacilityBundle\Entity\Facility::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}