<?php

namespace Volleyball\FacilityBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:59.
 */
class PasselQuartersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PasselQuarters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PasselQuarters;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}