parameters:
#    Volleyball_passel.example.class: Volleyball\PasselBundle\Example

services:
#    Volleyball_passel.example:
#        class: %Volleyball_passel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
