<?php

namespace Volleyball\UtilityBundle\Listener;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:56.
 */
class DoctrineExtensionListenerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DoctrineExtensionListener
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineExtensionListener;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UtilityBundle\Listener\DoctrineExtensionListener::setContainer
     * @todo   Implement testSetContainer().
     */
    public function testSetContainer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Listener\DoctrineExtensionListener::onLateKernelRequest
     * @todo   Implement testOnLateKernelRequest().
     */
    public function testOnLateKernelRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Listener\DoctrineExtensionListener::onKernelRequest
     * @todo   Implement testOnKernelRequest().
     */
    public function testOnKernelRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}