<?php

namespace Volleyball\EnrollmentBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:03.
 */
class ActiveEnrollmentControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ActiveEnrollmentController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ActiveEnrollmentController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::showAction
     * @todo   Implement testShowAction().
     */
    public function testShowAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::newAction
     * @todo   Implement testNewAction().
     */
    public function testNewAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::organizationAction
     * @todo   Implement testOrganizationAction().
     */
    public function testOrganizationAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::councilAction
     * @todo   Implement testCouncilAction().
     */
    public function testCouncilAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::regionAction
     * @todo   Implement testRegionAction().
     */
    public function testRegionAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::passelAction
     * @todo   Implement testPasselAction().
     */
    public function testPasselAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::attendeeAction
     * @todo   Implement testAttendeeAction().
     */
    public function testAttendeeAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::facilityAction
     * @todo   Implement testFacilityAction().
     */
    public function testFacilityAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Controller\ActiveEnrollmentController::weekAction
     * @todo   Implement testWeekAction().
     */
    public function testWeekAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}