departments:
    pattern: /departments
    defaults: { _controller: VolleyballFacilityBundle:Department:index }
departments_by_facility:
    pattern: /facilities/{facility}/departments
    defaults: { _controller: VolleyballFacilityBundle:Department:index }
departments_show:
    pattern: /facilities/{facility}/departments/{department}
    defaults: { _controller: VolleyballFacilityBundle:Department:show }
