facilities:
    resource: "@VolleyballFacilityBundle/Resources/config/routing/facility.yml"
    prefix: /
department:
    resource: "@VolleyballFacilityBundle/Resources/config/routing/department.yml"
    prefix: /
faculty:
    resource: "@VolleyballFacilityBundle/Resources/config/routing/faculty.yml"
    prefix: /
quarter:
    resource: "@VolleyballFacilityBundle/Resources/config/routing/quarters.yml"
    prefix: /
