<?php

namespace Volleyball\ReportBundle;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:00.
 */
class VolleyballReportBundleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var VolleyballReportBundle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VolleyballReportBundle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}