<?php

namespace Volleyball\OrganizationBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:02.
 */
class RegionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Region
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Region;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getPassels
     * @todo   Implement testGetPassels().
     */
    public function testGetPassels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::setPassels
     * @todo   Implement testSetPassels().
     */
    public function testSetPassels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::hasPassels
     * @todo   Implement testHasPassels().
     */
    public function testHasPassels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getPassel
     * @todo   Implement testGetPassel().
     */
    public function testGetPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::addPassel
     * @todo   Implement testAddPassel().
     */
    public function testAddPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::removePassel
     * @todo   Implement testRemovePassel().
     */
    public function testRemovePassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getFacilities
     * @todo   Implement testGetFacilities().
     */
    public function testGetFacilities()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::setFacilities
     * @todo   Implement testSetFacilities().
     */
    public function testSetFacilities()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::hasFacilities
     * @todo   Implement testHasFacilities().
     */
    public function testHasFacilities()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::addFacility
     * @todo   Implement testAddFacility().
     */
    public function testAddFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::removeFacility
     * @todo   Implement testRemoveFacility().
     */
    public function testRemoveFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::getFaculty
     * @todo   Implement testGetFaculty().
     */
    public function testGetFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::setFaculty
     * @todo   Implement testSetFaculty().
     */
    public function testSetFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::hasFaculty
     * @todo   Implement testHasFaculty().
     */
    public function testHasFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::addFaculty
     * @todo   Implement testAddFaculty().
     */
    public function testAddFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::removeFaculty
     * @todo   Implement testRemoveFaculty().
     */
    public function testRemoveFaculty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::addFacilitie
     * @todo   Implement testAddFacilitie().
     */
    public function testAddFacilitie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\OrganizationBundle\Entity\Region::removeFacilitie
     * @todo   Implement testRemoveFacilitie().
     */
    public function testRemoveFacilitie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}