<?php

namespace Volleyball\UtilityBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:57.
 */
class HomepageControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HomepageController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HomepageController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\HomepageController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\HomepageController::aboutAction
     * @todo   Implement testAboutAction().
     */
    public function testAboutAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\HomepageController::helpAction
     * @todo   Implement testHelpAction().
     */
    public function testHelpAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\HomepageController::contactAction
     * @todo   Implement testContactAction().
     */
    public function testContactAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}