<?php

namespace Volleyball\UtilityBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:56.
 */
class UtilityControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UtilityController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UtilityController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\UtilityController::setContainer
     * @todo   Implement testSetContainer().
     */
    public function testSetContainer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\UtilityController::getParameter
     * @todo   Implement testGetParameter().
     */
    public function testGetParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Controller\UtilityController::generateBreadcrumbs
     * @todo   Implement testGenerateBreadcrumbs().
     */
    public function testGenerateBreadcrumbs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}