<?php

namespace Volleyball\UtilityBundle\Menu;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:56.
 */
class MenuBuilderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MenuBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MenuBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UtilityBundle\Menu\MenuBuilder::createNonAuthMenu
     * @todo   Implement testCreateNonAuthMenu().
     */
    public function testCreateNonAuthMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Menu\MenuBuilder::createMainMenu
     * @todo   Implement testCreateMainMenu().
     */
    public function testCreateMainMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Menu\MenuBuilder::reportMenu
     * @todo   Implement testReportMenu().
     */
    public function testReportMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Menu\MenuBuilder::profileMenu
     * @todo   Implement testProfileMenu().
     */
    public function testProfileMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Menu\MenuBuilder::activeEnrollmentMenu
     * @todo   Implement testActiveEnrollmentMenu().
     */
    public function testActiveEnrollmentMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}