###############################################################################
## Reports
###############################################################################
reports:
    pattern: /reports
    defaults: { _controller: VolleyballReportBundle:Report:index }
reports_show:
    pattern: /reports/{report}
    defaults: { _controller: VolleyballReportBundle:Report:show }
report_new:
    pattern: /reports/new
    defaults: { _controller: VolleyballReportBundle:Report:new }
report_edit:
    pattern: /reports/{report}/edit
    defaults: { _controller: VolleyballReportBundle:Report:edit }
