<?php

namespace Volleyball\UserBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:00.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::registerAction
     * @todo   Implement testRegisterAction().
     */
    public function testRegisterAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::createAction
     * @todo   Implement testCreateAction().
     */
    public function testCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::aboutAction
     * @todo   Implement testAboutAction().
     */
    public function testAboutAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::helpAction
     * @todo   Implement testHelpAction().
     */
    public function testHelpAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UserBundle\Controller\UserController::contactAction
     * @todo   Implement testContactAction().
     */
    public function testContactAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}