<?php

namespace Volleyball\FacilityBundle\Repository;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:57.
 */
class FacultyRepositoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FacultyRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FacultyRepository;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\FacilityBundle\Repository\FacultyRepository::filterByFacility
     * @todo   Implement testFilterByFacility().
     */
    public function testFilterByFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}