<?php

namespace Volleyball\EnrollmentBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:05.
 */
class ActiveEnrollmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ActiveEnrollment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ActiveEnrollment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getOrganization
     * @todo   Implement testGetOrganization().
     */
    public function testGetOrganization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setOrganization
     * @todo   Implement testSetOrganization().
     */
    public function testSetOrganization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getCouncil
     * @todo   Implement testGetCouncil().
     */
    public function testGetCouncil()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setCouncil
     * @todo   Implement testSetCouncil().
     */
    public function testSetCouncil()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getRegion
     * @todo   Implement testGetRegion().
     */
    public function testGetRegion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setRegion
     * @todo   Implement testSetRegion().
     */
    public function testSetRegion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getPassel
     * @todo   Implement testGetPassel().
     */
    public function testGetPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setPassel
     * @todo   Implement testSetPassel().
     */
    public function testSetPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getAttendee
     * @todo   Implement testGetAttendee().
     */
    public function testGetAttendee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setAttendee
     * @todo   Implement testSetAttendee().
     */
    public function testSetAttendee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getLeader
     * @todo   Implement testGetLeader().
     */
    public function testGetLeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setLeader
     * @todo   Implement testSetLeader().
     */
    public function testSetLeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setFacility
     * @todo   Implement testSetFacility().
     */
    public function testSetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getSeason
     * @todo   Implement testGetSeason().
     */
    public function testGetSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setSeason
     * @todo   Implement testSetSeason().
     */
    public function testSetSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getWeek
     * @todo   Implement testGetWeek().
     */
    public function testGetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setWeek
     * @todo   Implement testSetWeek().
     */
    public function testSetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::getUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\ActiveEnrollment::setUser
     * @todo   Implement testSetUser().
     */
    public function testSetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}