<?php

namespace Volleyball\EnrollmentBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:05.
 */
class AttendeeEnrollmentCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AttendeeEnrollmentCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AttendeeEnrollmentCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::addEnrollment
     * @todo   Implement testAddEnrollment().
     */
    public function testAddEnrollment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::removeEnrollment
     * @todo   Implement testRemoveEnrollment().
     */
    public function testRemoveEnrollment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::getEnrollments
     * @todo   Implement testGetEnrollments().
     */
    public function testGetEnrollments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::setAttendee
     * @todo   Implement testSetAttendee().
     */
    public function testSetAttendee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::getAttendee
     * @todo   Implement testGetAttendee().
     */
    public function testGetAttendee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::setFacility
     * @todo   Implement testSetFacility().
     */
    public function testSetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::setWeek
     * @todo   Implement testSetWeek().
     */
    public function testSetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\AttendeeEnrollmentCollection::getWeek
     * @todo   Implement testGetWeek().
     */
    public function testGetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}