<?php

namespace Volleyball\EnrollmentBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:05.
 */
class PasselEnrollmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PasselEnrollment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PasselEnrollment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setPassel
     * @todo   Implement testSetPassel().
     */
    public function testSetPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getPassel
     * @todo   Implement testGetPassel().
     */
    public function testGetPassel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setFacility
     * @todo   Implement testSetFacility().
     */
    public function testSetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setWeek
     * @todo   Implement testSetWeek().
     */
    public function testSetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getWeek
     * @todo   Implement testGetWeek().
     */
    public function testGetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setSeason
     * @todo   Implement testSetSeason().
     */
    public function testSetSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getSeason
     * @todo   Implement testGetSeason().
     */
    public function testGetSeason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setQuarters
     * @todo   Implement testSetQuarters().
     */
    public function testSetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getQuarters
     * @todo   Implement testGetQuarters().
     */
    public function testGetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\PasselEnrollment::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}