<?php

namespace Volleyball\EnrollmentBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:05.
 */
class PeriodTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Period
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Period;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getWeek
     * @todo   Implement testGetWeek().
     */
    public function testGetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setWeek
     * @todo   Implement testSetWeek().
     */
    public function testSetWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getStart
     * @todo   Implement testGetStart().
     */
    public function testGetStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setStart
     * @todo   Implement testSetStart().
     */
    public function testSetStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getEnd
     * @todo   Implement testGetEnd().
     */
    public function testGetEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setEnd
     * @todo   Implement testSetEnd().
     */
    public function testSetEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::isSpecial
     * @todo   Implement testIsSpecial().
     */
    public function testIsSpecial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setSpecial
     * @todo   Implement testSetSpecial().
     */
    public function testSetSpecial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getSpecial
     * @todo   Implement testGetSpecial().
     */
    public function testGetSpecial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Period::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}