<?php

namespace Volleyball\EnrollmentBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:23:05.
 */
class SeasonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Season
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Season;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getYear
     * @todo   Implement testGetYear().
     */
    public function testGetYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setYear
     * @todo   Implement testSetYear().
     */
    public function testSetYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getFacility
     * @todo   Implement testGetFacility().
     */
    public function testGetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setFacility
     * @todo   Implement testSetFacility().
     */
    public function testSetFacility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\EnrollmentBundle\Entity\Season::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}