parameters:
#    Volleyball_facility.example.class: Volleyball\FacilityBundle\Example

services:
#    Volleyball_facility.example:
#        class: %Volleyball_facility.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
