<?php

namespace Volleyball\UtilityBundle\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:55.
 */
class ResourceEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ResourceEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResourceEvent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\UtilityBundle\Event\ResourceEvent::stop
     * @todo   Implement testStop().
     */
    public function testStop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Event\ResourceEvent::isStopped
     * @todo   Implement testIsStopped().
     */
    public function testIsStopped()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Event\ResourceEvent::getMessageType
     * @todo   Implement testGetMessageType().
     */
    public function testGetMessageType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Event\ResourceEvent::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\UtilityBundle\Event\ResourceEvent::getMessageParameters
     * @todo   Implement testGetMessageParameters().
     */
    public function testGetMessageParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}