<?php

namespace Volleyball\PasselBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 19:22:54.
 */
class PositionControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PositionController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PositionController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Volleyball\PasselBundle\Controller\PositionController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\PasselBundle\Controller\PositionController::newAction
     * @todo   Implement testNewAction().
     */
    public function testNewAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\PasselBundle\Controller\PositionController::searchAction
     * @todo   Implement testSearchAction().
     */
    public function testSearchAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Volleyball\PasselBundle\Controller\PositionController::showAction
     * @todo   Implement testShowAction().
     */
    public function testShowAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}