parameters:
#    Volleyball_organization.example.class: Volleyball\OrganizationBundle\Example

services:
#    Volleyball_organization.example:
#        class: %Volleyball_organization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
