classes_by_week:
    pattern: /facilities/{facility}/{week}/classes
    defaults: { _controller: VolleyballCourseBundle:VbClass:index }
classes_by_period:
    pattern: /facilities/{facility}/{week}/{period}/classes
    defaults: { _controller: VolleyballCourseBundle:VbClass:index }
class_show:
    pattern: /facilities/{facility}/classes/{class}
    defaults: { _controller: VolleyballCourseBundle:VbClass:show }
