meritbadges:
    pattern: /meritbadges
    defaults: { _controller: VolleyballCourseBundle:MeritBadge:index }
meritbadge_show:
    pattern: /meritbadges/{meritbadge}
    defaults: { _controller: VolleyballCourseBundle:MeritBadge:show }
